# Generated by Django 5.0.7 on 2024-07-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('music', 'Música'), ('show', 'Show'), ('museum', 'Museu')], max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('pt', 'Português'), ('de', 'Alemão')], max_length=2)),
                ('image', models.ImageField(upload_to='events/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
